### ISSUE TITLE
CSS文件加载不了

### ISSUE THREAD

**Issue by jmx164491960** [Yiiu/vue-blog#2]

**Comment by Yiiu** [comment]
修复了，运行npm run build就好啦

**Comment by jmx164491960** [comment]
十分感谢

**Comment by jmx164491960** [comment]
const { wrap: async } = require('co');这句报错。请问这是什么写法？？

**Comment by Yiiu** [comment]
@jmx164491960 我这里没有报错欸，你用的是4.x版本嘛，这句话就是把co的wrap模块导入

**Comment by Yiiu** [comment]
@jmx164491960 用 " node --harmony_destructuring app.js"运行试试
